# Generated by Django 4.1.13 on 2024-06-18 10:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=500)),
                ('job_post_url', models.CharField(max_length=100)),
                ('job_apply_url', models.CharField(max_length=100)),
                ('company_url', models.CharField(max_length=100)),
                ('company_industry', models.CharField(max_length=1000)),
                ('min_compensation', models.CharField(max_length=10)),
                ('max_compensation', models.CharField(max_length=10)),
                ('type_of_compensation', models.CharField(choices=[('annual', 'Annual'), ('hourly', 'Hourly')], max_length=6)),
                ('job_hours', models.CharField(max_length=10)),
                ('role_seniority', models.CharField(choices=[('MidLevel', 'Mid-Level'), ('EntryLevel', 'Entry-Level'), ('TeamLead', 'Team_Lead')], max_length=10)),
                ('min_education', models.CharField(max_length=20)),
                ('office_location', models.CharField(choices=[('Hybrid', 'Hybrid'), ('InOffice', 'In-Office'), ('WorkFromHome', 'work-from-home')], max_length=100)),
                ('post_html', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
